routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Departamentos

Route::resource('departamentos', 'DepartamentosController');   

Route::get('departments', function(){

    return view('departamentos.index');
});

// Ciudades

Route::resource('ciudades', 'CiudadesController');

Route::get('cities', function(){

    return view('ciudades.index');
});

// Agentes

Route::resource('agentes', 'AgentesController');   

Route::get('agents', function(){

    return view('agentes.index');
});

// Clientes

Route::resource('clientes', 'ClientesController');

Route::get('clientes/update/{cliente}', [

    'uses' => 'ClientesController@update',
    'as' => 'clientes.update'
]); 

Route::get('clientes/destroy/{cliente}', [

    'uses' => 'ClientesController@destroy',
    'as' => 'clientes.destroy'
]); 

Route::get('customers', function(){

    return view('clientes.index');
});

app/Http/Controllers/CiudadesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Ciudad;
use App\Departamento;

class CiudadesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ciudades = DB::table('ciudades')
        ->join('departamentos', 'ciudades.id_departamento', '=', 'departamentos.id')
        ->select('ciudades.id AS id_ciudad', 'ciudades.nombre AS nombre_ciudad', 'departamentos.id AS id_departamento', 'departamentos.nombre AS nombre_departamento')->get();
        return $ciudades;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departamentos = Departamento::all();
        return view('ciudades.add')->with('departamentos', $departamentos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ciudad = new Ciudad( $request->all() );

        if ( $ciudad->save() ){
            
            $result = 1; 

        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ciudad = Ciudad::find($id);
        $ciudad->fill( $request->all() );

        if( $ciudad->save() ){

            $result = 1;
        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ciudad = Ciudad::find($id);

        if( $ciudad->delete() ){

            $result = 1;

        } else{

            $result = 0;
        }

        return $result;
    }
}

resources/views/ciudades/add.blade.php
@extends('template.master')

@section('title', 'Ciudades')

@section('action', 'Agregar')

@section('content')

<div class="card" ng-controller="ciudades as ct">
    <div class="card-block">
        <form class="form-horizontal form-material">
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="nombre">Nombre</label>
                    <input ng-model="ct.nombre" id="nombre" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="nombre">Departamento</label>
                    <select ng-model="ct.departamento" id="departamento"  class="form-control">
                        @foreach($departamentos as $departamento)
                            <option value="{{$departamento->id}}"> {{$departamento->nombre}} </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">                    
                    <button  ng-click="ct.agregarCiudad()" class="btn btn-success">Agregar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/ciudades/index.blade.php
@extends('template.master')

@section('title', 'Ciudades')

@section('action', 'Lista')

@section('content')

    <div class="card" ng-controller="ciudades as ct">
        <div class="card-block">
        <a class="addIcon" href="{{route('ciudades.create')}}"> <i class="mdi mdi-library-plus"></i> Agregar Ciudad  </a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Departamento</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="ciudad in ct.ciudades">
                            <td> @verbatim {{ ciudad.nombre_ciudad }} @endverbatim </td>
                            <td> @verbatim {{ ciudad.nombre_departamento }} @endverbatim </td>                                                 
                        </tr>                                          
                    </tbody>
                </table>
            </div>
        </div>        
    </div>    

@endsection