routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Departamentos

Route::resource('departamentos', 'DepartamentosController');   

Route::get('departments', function(){

    return view('departamentos.index');
});

// Ciudades

Route::resource('ciudades', 'CiudadesController');

Route::get('cities', function(){

    return view('ciudades.index');
});

// Agentes

Route::resource('agentes', 'AgentesController');   

Route::get('agents', function(){

    return view('agentes.index');
});

// Clientes

Route::resource('clientes', 'ClientesController');

Route::get('clientes/update/{cliente}', [

    'uses' => 'ClientesController@update',
    'as' => 'clientes.update'
]); 

Route::get('clientes/destroy/{cliente}', [

    'uses' => 'ClientesController@destroy',
    'as' => 'clientes.destroy'
]); 

Route::get('customers', function(){

    return view('clientes.index');
});

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = "clientes";

    protected $fillable = [
        'nombre', 
        'num_identificacion', 
        'num_celular', 
        'direccion', 
        'id_agente', 
        'id_ciudad'       
    ];

    public function agente(){

        return $this->belongsTo('App\Agente');
    }

    public function usuario(){

        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Cliente;
use App\Agente;
use App\Ciudad;

class ClientesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = DB::table('clientes')
        ->join('agentes', 'clientes.id_agente', '=', 'agentes.id')
        ->join('ciudades', 'clientes.id_ciudad', '=', 'ciudades.id')
        ->select('clientes.nombre AS nombre_cliente', 'clientes.num_identificacion', 'clientes.num_celular', 'clientes.direccion', 'agentes.nombre AS nombre_agente', 'ciudades.nombre AS nombre_ciudad', 'clientes.id AS id_cliente', 'agentes.id AS id_agente', 'ciudades.id AS id_ciudad')
        ->get();
        return $clientes;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $agentes = Agente::all();
        $ciudades = Ciudad::all();

        return view('clientes.add', ['agentes' => $agentes, 'ciudades'  => $ciudades]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cliente = new Cliente( $request->all() );

        if ( $cliente->save() ){
            
            $result = 1; 

        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cliente = Cliente::find($id);
        $cliente->fill( $request->all() );

        if( $cliente->save() ){

            $result = 1;
        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cliente =  Cliente::find($id);

        if( $cliente->delete() ){

            $result = 1;
        } else{

            $result = 0;
        }

        return $result;
    }
}

resources/views/clientes/add.blade.php
@extends('template.master')

@section('title', 'Clientes')

@section('action', 'Agregar')

@section('content')

<div class="card" ng-controller="clientes as cl">
    <div class="card-block">
        <form class="form-horizontal form-material">
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="nombre">Nombre</label>
                    <input ng-model="cl.nombre" id="nombre" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="num_identificacion">Número de identificación</label>
                    <input ng-model="cl.num_identificacion" id="num_identificacion" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="num_celular">Número de celular</label>
                    <input ng-model="cl.num_celular" id="num_celular" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="direccion">Dirección</label>
                    <input ng-model="cl.direccion" id="direccion" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="agente">Agente</label>
                    <select name="" id="agente" class="form-control" ng-model="cl.agente">
                        @foreach($agentes as $agente)
                            <option value="{{$agente->id}}"> {{$agente->nombre}} </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="ciudad">Ciudad</label>
                    <select name="" id="ciudad" class="form-control" ng-model="cl.ciudad">
                        @foreach($ciudades as $ciudad)
                            <option value="{{$ciudad->id}}"> {{$ciudad->nombre}} </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">                    
                    <button  ng-click="cl.agregarCliente()" class="btn btn-success">Agregar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/clientes/index.blade.php
@extends('template.master')

@section('title', 'Clientes')

@section('action', 'Lista')

@section('content')

    <div class="card" ng-controller="clientes as cl">
        <div class="card-block">
            <a class="addIcon" href="{{route('clientes.create')}}"> <i class="mdi mdi-library-plus"></i> Agregar Cliente </a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>    
                            <th>Número de identificación</th>
                            <th>Número de celular</th>
                            <th>Dirección</th>
                            <th>Agente</th>
                            <th>Ciudad</th>           
                            <th>Acciones</th>             
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="cliente in cl.clientes">
                            <td> @verbatim {{ cliente.nombre_cliente }} @endverbatim </td>
                            <td> @verbatim {{ cliente.num_identificacion }} @endverbatim </td>
                            <td> @verbatim {{ cliente.num_celular }} @endverbatim </td>        
                            <td> @verbatim {{ cliente.direccion }} @endverbatim </td>     
                            <td> @verbatim {{ cliente.nombre_agente }} @endverbatim </td>   
                            <td> @verbatim {{ cliente.nombre_ciudad }} @endverbatim </td>   
                            <td>
                                <button class="btn" data-toggle="modal" data-target="#modalClientes" ng-click="cl.obtenerInformacion(cliente.nombre_cliente, cliente.num_identificacion, cliente.num_celular, cliente.direccion, cliente.id_cliente, cliente.id_agente, cliente.id_ciudad)"><i class="mdi mdi-grease-pencil"></i></button>
                                <button class="btn" ng-click="cl.eliminarCliente(cliente.id_cliente)"><i class="mdi mdi-delete"></i></button>
                            </td>                                
                        </tr>                                          
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Modal de edición -->

        <div class="modal fade" id="modalClientes">
            <div class="modal-dialog">
                <div class="modal-dialog">
                    <div align="right" class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-content">
                        <div class="container">
                            <h3> Edición de Cliente </h3>
                            <form class="form-horizontal form-material">
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="nombre">Nombre</label>
                                        <input id="nombre" type="text" class="form-control" ng-model="cl.nombre">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="num_identificacion">Número de identificación</label>
                                        <input id="num_identificacion" type="text" class="form-control" ng-model="cl.num_identificacion">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="num_celular">Número de celular</label>
                                        <input id="num_celular" type="text" class="form-control" ng-model="cl.num_celular">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="direccion">Dirección</label>
                                        <input id="direccion" type="text" class="form-control" ng-model="cl.direccion">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="agente">Agente</label>
                                        <select id="agente" class="form-control" ng-model="cl.agente">
                                            <option ng-repeat="agente in cl.agentes" @verbatim value="{{ agente.id }}">  {{ agente.nombre }} @endverbatim </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <label for="ciudad">Ciudad</label>
                                        <select id="ciudad" class="form-control" ng-model="cl.ciudad">
                                            <option ng-repeat="ciudad in cl.ciudades" @verbatim value="{{ ciudad.id_ciudad }}">  {{ ciudad.nombre_ciudad }} @endverbatim </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <button class="btn btn-success" ng-click="cl.actualizarCliente()">Editar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    

@endsection