routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Departamentos

Route::resource('departamentos', 'DepartamentosController');   

Route::get('departments', function(){

    return view('departamentos.index');
});

// Ciudades

Route::resource('ciudades', 'CiudadesController');

Route::get('cities', function(){

    return view('ciudades.index');
});

// Agentes

Route::resource('agentes', 'AgentesController');   

Route::get('agents', function(){

    return view('agentes.index');
});

// Clientes

Route::resource('clientes', 'ClientesController');

Route::get('clientes/update/{cliente}', [

    'uses' => 'ClientesController@update',
    'as' => 'clientes.update'
]); 

Route::get('clientes/destroy/{cliente}', [

    'uses' => 'ClientesController@destroy',
    'as' => 'clientes.destroy'
]); 

Route::get('customers', function(){

    return view('clientes.index');
});

app/Agente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agente extends Model
{
    protected $table = "agentes";

    protected $fillable = ['num_identificacion', 'nombre'];

    public function clientes(){

        return $this->hasMany('App\Cliente');
    }
}

app/Http/Controllers/AgentesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Agente;

class AgentesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agentes = Agente::all();
        return $agentes;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        return view('agentes.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $agente = new Agente( $request->all() );

        if ( $agente->save() ){
            
            $result = 1; 

        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $agente = Agente::find($id);
        $agente->fill( $request->all() );

        if( $agente->save() ){

            $result = 1;
        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $agente = Agente::find($id);

        if( $agente->delete() ){

            $result = 1;

        } else{

            $result = 0;
        }

        return $result;
    }
}

resources/views/agentes/add.blade.php
@extends('template.master')

@section('title', 'Agentes')

@section('action', 'Agregar')

@section('content')

<div class="card" ng-controller="agentes as ag">
    <div class="card-block">
        <form class="form-horizontal form-material">
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="nombre">Nombre</label>
                    <input ng-model="ag.nombre" id="nombre" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="nombre">Número de identificación</label>
                    <input class="form-control" ng-model="ag.num_identificacion" type="text" name="" id="num_identificación">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">                    
                    <button  ng-click="ag.agregarAgentes()" class="btn btn-success">Agregar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/agentes/index.blade.php
@extends('template.master')

@section('title', 'Agentes')

@section('action', 'Lista')

@section('content')

    <div class="card" ng-controller="agentes as ag">
        <div class="card-block">
        <a class="addIcon" href="{{route('agentes.create')}}"> <i class="mdi mdi-library-plus"></i> Agregar Agentes  </a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Numero de identificación</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="agente in ag.agentes">
                            <td> @verbatim {{ agente.nombre }} @endverbatim </td>
                            <td> @verbatim {{ agente.num_identificacion }} @endverbatim </td>                                                 
                        </tr>                                          
                    </tbody>
                </table>
            </div>
        </div>        
    </div>    

@endsection