routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Departamentos

Route::resource('departamentos', 'DepartamentosController');   

Route::get('departments', function(){

    return view('departamentos.index');
});

// Ciudades

Route::resource('ciudades', 'CiudadesController');

Route::get('cities', function(){

    return view('ciudades.index');
});

// Agentes

Route::resource('agentes', 'AgentesController');   

Route::get('agents', function(){

    return view('agentes.index');
});

// Clientes

Route::resource('clientes', 'ClientesController');

Route::get('clientes/update/{cliente}', [

    'uses' => 'ClientesController@update',
    'as' => 'clientes.update'
]); 

Route::get('clientes/destroy/{cliente}', [

    'uses' => 'ClientesController@destroy',
    'as' => 'clientes.destroy'
]); 

Route::get('customers', function(){

    return view('clientes.index');
});

app/Departamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Departamento extends Model
{
    protected $table = "departamentos";

    protected $fillable = ['nombre'];
    
    public function ciudades(){

        return  $this->hasMany('App\Ciudad');
    }
}

app/Http/Controllers/DepartamentosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Departamento;

class DepartamentosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departamentos = Departamento::all();
        return $departamentos;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('departamentos.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $departamento = new Departamento( $request->all() );

        if ( $departamento->save() ){
            
            $result = 1; 

        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $departamento = Departamento::find($id);
        $departamento->fill( $request->all() );

        if( $departamento->save() ){

            $result = 1;
        } else{

            $result = 0;
        }

        return $result;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $departamento =  Departamento::find($id);

        if( $departamento->delete() ){

            $result = 1;
        } else{

            $result = 0;
        }

        return $result;
    }
}

resources/views/departamentos/add.blade.php
@extends('template.master')

@section('title', 'Departamentos')

@section('action', 'Agregar')

@section('content')

<div class="card" ng-controller="listarDepartamentos as ld">
    <div class="card-block">
        <form class="form-horizontal form-material">
            <div class="form-group">
                <div class="col-xs-12">
                    <label for="nombre">Nombre</label>
                    <input ng-model="ld.nombre" id="nombre" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">                    
                    <button  ng-click="ld.agregarDepartamento()" class="btn btn-success">Agregar</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/departamentos/index.blade.php
@extends('template.master')

@section('title', 'Departamentos')

@section('action', 'Lista')

@section('content')

    <div class="card" ng-controller="listarDepartamentos as ld">
        <div class="card-block">
            <a class="addIcon" href="{{route('departamentos.create')}}"> <i class="mdi mdi-library-plus"></i> Agregar Departamento  </a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nombre</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="departamento in ld.departamentos">
                            <td> @verbatim {{ departamento.nombre }} @endverbatim </td>                                                 
                        </tr>                                          
                    </tbody>
                </table>
            </div>
        </div>        
    </div>


    

@endsection